### ISSUE TITLE
The future of Orders API for SCA

### ISSUE THREAD

**Issue by luketsimmons** [stripe/sca-dev-chats#1]
## Topic

What exactly is happening to the Orders API. We heavily rely on this flow and the use of "off time invoices" isn't necessarily feasible.
Is it true there are no plans to do anything ahead of September?
What if there only needs to be minor updates to say the Order->update() method?
We have investigated and constructed an almost working flow with PaymentIntents and Orders. It just requires an update to the Orders API to allow us to attach the Charge ID generated from the PaymentIntent to the Order and set the status as "paid". Could this be something for Orders API. Alternatively, what do we do? Thanks! Luke

ps. Love the dev chat and thanks for doing these!

## API

What API does your question relate to: Orders API, PaymentIntents, Charges

## Stripe Products

What Stripe Products are you using: Payments, Billing, Orders, etc

## Tech stack

- Backend language/frameworks: PHP
- Frontend libraries/frameworks: JS / jQuery
- Stripe API version: 2018-02-28 (for good reason :D )
- Stripe library version: Stripe v1 6.41.0

**Comment by thorsten-stripe** [comment]
@luketsimmons thanks for reaching out! Two follow up questions if I may:
1) What functionality are "One-off Invoices" lacking that don't make them feasible for your use case?
2) You say you're on API v. 2018-02-28 for good reason, are you able to share that reason? What prohibits you from upgrading to a more recent version?

That would be very helpful context for us :) In the meantime I will check with the team regarding your ask to update an order object with a successful charge to move it into paid state.

**Comment by luketsimmons** [comment]
@thorsten-stripe no worries, thanks for the reply!

1. We rely quite heavily on the whole Orders API setup, specifically with regards to Products. We have over 1200 "digital products" which have costs attached to SKUs. The users buy these Products and so we create and Order, apply line items such as coupons/discounts/VAT and then Stripe charges the user, closes the Order as paid and the user then has access within our system to the Product. We then have a catalogue of Orders which aligns with user data in our CMS.

Discussing with the Stripe SCA team, it was suggested that our Products as they currently exist in Orders would not work with the One-off Invoices approach. We would therefore need recreate the Products and also switch to Checkout, which we definitely do not want to do at this time. 

So it's quite an involved migration, whereas the suggestion of allowing the Orders API to update an Order and add the Charge ID returned from the success PaymentIntent (thus marking the Order as paid - which is currently automated?) "should" suitable fit our existing model with minimal changes. Does that make sense?

2. LOL. So the secondary reason is time and effort. But the main reason is - **2018-05-21
Products no longer have SKU lists embedded.** this change to the API appeared to be a blocker in how we were able to load Products using their SKUs. We use a UUID from our CMS to associate the Product in our system with the SKU (basically cost relationship) in Stripe. 

This fitted very well when we created the relationship in 2016. The change however means we cannot directly load a Product using the UUID so we have to engineer a way to change the relationship with our CMS and Stripe. Again the reason this hasn't happened is a) time and effort, and b) no real urgency on updating our API version to a later release (there were no major benefits to be had in the updates).

Again, hopefully that makes sense?!

If you can discuss with the team (I think someone from Support is doing the same, but I won't deter multiple requests 😄 ) that would be hugely appreciated!

Thanks again,
Luke

**Comment by thorsten-stripe** [comment]
Thanks @luketsimmons very much appreciate the level of detail! I've checked with the team, and unfortunately as it stands today there are no plans to upgrade the Orders API for SCA/usage with PaymentIntents. 

While I agree that updating the Order object with a successful charge would be a neat approach, the team has currently not scoped this work and therefore the guidance is to migrate to invoices, or in your case potentially Checkout Session with `line_items` (https://stripe.com/docs/api/checkout/sessions/create#create_checkout_session-line_items) could work.

You can create the Checkout session server_side, passing in the line_item information of your products and pass `expand[]=payment_intent` to get the payment state machine with the total amount and status etc: https://runkit.com/thor-stripe/5d51a446e05d87001a52e79c

I hope this will help you carve out a migration path, and sorry that this has turned out so onerous for you :(

**Comment by luketsimmons** [comment]
Hi @thorsten-stripe, thank you also for the response! I assume that means we won't be making the next dev chat as a subject?! 😁 

It's a shame that even though you agree (and a few others from Stripe support!) about my approach it still won't be making an appearance 😞 . Migrating to invoices just seems like a half-cocked approach when all our products are not available to Invoices (from what I've been led to believe as they are Orders Products) ??

That said, while we haven't previously wanted to use Checkout (Elements is so good with a custom design), I think what you are suggesting sounds interesting. I want to still pursue Orders if hopefully Stripe Devs are able to do anything to help the community of Online Retailers that are affected by SCA whom use Orders... but I'll check out Checkout (excuse the pun) in the meantime.

Thanks again for your help and detailed response, looking forward to the Livestream on Wednesday!

Luke
