### ISSUE TITLE
3D Secure 2 Card not working with handleCardPayment

### ISSUE THREAD

**Issue by tbell511** [stripe/sca-dev-chats#10]
## Topic

I've found what appears to be some unusual behavior.

Using test card 4000000000003063 (3D Secure) during checkout results in a paymentIntent with a `requires_action` status. Passing the `client_secret` to `handleCardPayment` results in Stripe's 3D Secure Test Payment modal.  If I refresh the page, and use `handleCardPayment` again, the 3D Secure Test modal appears again.  Everything works perfectly 👍  

Using test card 4000000000003220 (3D Secure 2) is not working the same way. Passing it's `client_secret` to `handleCardPayment` does make Stripes 3D Secure 2 modal appear the first time. However, refreshing the page and using `handleCardPayment` again, results in no modal appearing and it returns the following result.

```
{
  "paymentIntent": {
    "id": "pi_1F8e3EKQYPov2Q6Daqclu7t0",
    "object": "payment_intent",
    "allowed_source_types": [
      "card"
    ],
    "amount": 2500,
    "canceled_at": null,
    "cancellation_reason": null,
    "capture_method": "automatic",
    "client_secret": "pi_1F8e3EKQYPov2Q6Daqclu7t0_secret_L1sFIGu88LwKXdpozj83kqfFh",
    "confirmation_method": "automatic",
    "created": 1566095004,
    "currency": "usd",
    "description": "Payment for invoice 12E7B181-0001",
    "last_payment_error": null,
    "livemode": false,
    "next_action": {
      "type": "use_stripe_sdk",
      "use_stripe_sdk": {
        "type": "stripe_3ds2_challenge",
        "stripe_js": {
          "three_d_secure_2_source": "src_1F8e3FKQYPov2Q6DfCgqdKE8",
          "directory_server_name": "visa",
          "server_transaction_id": "4bdbd5a9-be49-4fc7-ab4e-8a4fe5a705a5",
          "acs_transaction_id": "fca20147-b2c6-4add-aca3-8aa511579bf9",
          "acs_url": "https://hooks.stripe.com/3d_secure_2_test/challenge",
          "three_ds_optimizations": ""
        }
      }
    },
    "next_source_action": {
      "type": "use_stripe_sdk",
      "use_stripe_sdk": {
        "type": "stripe_3ds2_challenge",
        "stripe_js": {
          "three_d_secure_2_source": "src_1F8e3FKQYPov2Q6DfCgqdKE8",
          "directory_server_name": "visa",
          "server_transaction_id": "4bdbd5a9-be49-4fc7-ab4e-8a4fe5a705a5",
          "acs_transaction_id": "fca20147-b2c6-4add-aca3-8aa511579bf9",
          "acs_url": "https://hooks.stripe.com/3d_secure_2_test/challenge",
          "three_ds_optimizations": ""
        }
      }
    },
    "payment_method": "pm_1F8e3DKQYPov2Q6DQS3Hwcb8",
    "payment_method_types": [
      "card"
    ],
    "receipt_email": null,
    "setup_future_usage": "off_session",
    "shipping": null,
    "source": null,
    "status": "requires_source_action"
  }
}
```

Is this suppose to happen?

Thanks!

## API

What API does your question relate to: PaymentIntents, handleCardPayment

## Stripe Products

What Stripe Products are you using: Billing

## Tech stack

- Backend language/frameworks: Node
- Frontend libraries/frameworks: n/a
- Stripe API version: 2019-05-16
- Stripe library version: stripe.js

**Comment by tbell511** [comment]
Has anyone been able to replicate this? 😃

**Comment by mikeshaw-stripe** [comment]
Hey @tbell511, going to try in a few mins. I will let you know if I can repro

**Comment by tbell511** [comment]
Thanks Mike!

**Comment by mikeshaw-stripe** [comment]
Hey @tbell511. I could reproduce the bug and we are planning on releasing a fix today. Thanks for flagging :)

I'll wait to verify the fix before we close this issue

**Comment by tbell511** [comment]
Sounds great, thanks for looking into it!

**Comment by tbell511** [comment]
Seems like the bug has been fixed 👍
