### ISSUE TITLE
unable to update api from https://dashboard.stripe.com/test/developers

### ISSUE THREAD

**Issue by soju-ti** [stripe/sca-dev-chats#13]
## Topic

referring to adis code @ https://github.com/adi-stripe/public-testing-tools/tree/master/billing when i try to create a new subscription using PaymentMethod i got `Payment for this subscription requires additional user action before it can be completed successfully`.
here are the following steps i followed

1)create a customer
2)attach payment method to customer
3)using the payment method id i create a subscription
4)get the payment method id from client side using `createPaymentMethod` api

## Stripe Products

What Stripe Products are you using: Billing

## Tech stack

- Backend language/frameworks: <PHP.>
- Frontend libraries/frameworks: <Vue>
- Stripe library version: <Stripe6.28.0>

**Comment by soju-ti** [comment]
issue due to not updating api version in
https://dashboard.stripe.com/test/developers

but in my case update button is disabled and a tooltip pops up and says `version change can only be made in live mode switch to live mode to upgrade or rollback`

**Comment by jperasmus** [comment]
This sounds like you have the "Viewing test data" setting in the Stripe dashboard switched on (ie. you are in test mode).

Unselect this setting if it is selected.

**Comment by soju-ti** [comment]
hmm.. but i need to work this in test mode. seems like i need to set 
`\Stripe\Stripe::setApiVersion("2019-08-14")` .am i correct?

**Comment by jperasmus** [comment]
Yeah, you'll have to explicitly set it as you showed in your code while you're existing production code runs with the old API version. Then once you roll out these changes successfully, you can upgrade the API version in the Stripe dashboard and remove the explicit version from your code.

As far as I could tell, you can not specify a different API version for the live and production version from within the Stripe dashboard.

**Comment by thorsten-stripe** [comment]
@soju-ti yes, please set the API version either via the backend, or create a new test account (which will then be created with the newest API version by default)[0]. Thanks @jperasmus for helping out here :)

[0] https://stripe.com/docs/multiple-accounts
