### ISSUE TITLE
Capture new card details using Checkout for requires_authentication failed PaymentIntent

### ISSUE THREAD

**Issue by warksit** [stripe/sca-dev-chats#18]
## Topic

I am using SetupIntents and Checkout to capture card details for later off-session processing.

Then at a later date I am creating an off-session PaymentIntent using the payment method captured above.

In the scenario where this fails due to requires_authentication what I would like to do is get the customer back on-session and offer them 2 options.

1. Authenticate previously entered card
2. Enter new card using Stripe Checkout

I am good with 1 but I can't see how to do 2.

## API

What API does your question relate to: <PaymentIntents|SetupIntents>

## Stripe Products

What Stripe Products are you using: <Payments|Checkout>

## Tech stack

- Backend language/frameworks: PHP
- Frontend libraries/frameworks: Vue (but just testing with vanilla js for now)
- Stripe API version: 2019-09-09
- Stripe library version: Stripe v1 7.1.1

**Comment by warksit** [comment]
I am aware I can do this with stripe elements but I would prefer to use Stripe Checkout for consistency throughout the site.

**Comment by adi-stripe** [comment]
Hello, 

My assumption is you want to capture a payment and save the card for future off-session use via Checkout. 

You can do this by following our docs for capturing one time payments [1]. Make sure you populate the field payment_intent_data.setup_future_usage[2]. This will allow you to reuse the Payment Method.

Hope this clarifies. Let me know if you still have questions :) 

[1] https://stripe.com/docs/payments/checkout/server
[2] https://stripe.com/docs/api/checkout/sessions/create#create_checkout_session-payment_intent_data-setup_future_usage

**Comment by warksit** [comment]
My specific question is capturing new card details for a PaymentIntent that has failed due to requires_authentication. The checkout appears to only work with sessions not paymentIntents?

**Comment by adi-stripe** [comment]
@warksit indeed, the payment_intent_data.setup_future_usage is a parameter on the Checkout Session object. Let me know if this clarifies. 

https://stripe.com/docs/api/checkout/sessions/create#create_checkout_session-payment_intent_data-setup_future_usage

**Comment by warksit** [comment]
I don’t seem to be communicating very well. Let’s say I have a payment intent that was created using a checkout session with payment_intent_data.setup_future_usage specified correctly. So long as the bank authorise this is all functional when I take a payment against the payment intent attached to a customer. 

BUT if this payment attempt fails leaving the paymentIntent with requires_authorisation how do I capture new card details to use against that payment intent?

**Comment by slybridges** [comment]
I had a similar question and I ended up listening to the payment and authentication failed webhook events that contains a link to the hosted invoice page where the user can authenticate and/or enter new card details.

See #11 for details.

**Comment by adi-stripe** [comment]
Hello @warksit ,
Really sorry for the confusion here. 

For the failed off-session payment 
(1) Use SetupIntents and Checkout to capture new card details 
(2) Update the Payment Method on the existing Payment Intent 
(3) authenticate the PaymentIntent if requires_action

Let me know if this clarifies.

**Comment by warksit** [comment]
HI @adi-stripe that makes sense, will take a go at that.
