### ISSUE TITLE
Updating default cards

### ISSUE THREAD

**Issue by ccnklc** [stripe/sca-dev-chats#21]
## Topic

What is your question?

I can clearly see that i can use pending setup intents to authorize a card and save it for recurring default payments, however there is no clear direction for me on how to update a subscription default payment method while subscription is active, there is no setupintent in subscription object and because setupIntents are created automatically for subscriptions, i have no idea how to authorize the new card and get it ready for off session payments while updating default payment method for customer/subscription.

I can easily update either subscription or customer default payment method however it doesn't create an automatic setup intent for authorization. And i don't want customers to face with an authorization issue when the next invoice is generated and stripe automatically tries to charge the new default method.

Should i just create an empty setupIntent, authorize the card at frontend, if successful attach it to customer  then add it as a default payment method on customer or subscription and expect it to work? As there is no docs for this on billing section i am not sure if this is the right approach.

## API

What API does your question relate to: 
It is related to SetupIntents

## Stripe Products

What Stripe Products are you using: 
Billing

## Tech stack

- Backend language/frameworks: Node
- Frontend libraries/frameworks: React
- Stripe API version: 2019-09-09
- Stripe library version: "react-stripe-elements": "^4.0.0", "stripe": "^7.5.0"

**Comment by lifenautjoe** [comment]
Holy cow, 8 days and no clue of an answer.. GG Stripe!

**Comment by adi-stripe** [comment]
Hello , 

There are two scenarios when replacing a Payment Methods on existing Subscriptions. 
Will add below my suggested paths. 

**Scenario 1 (collect a new Payment Method - without paying an invoice)**
This is the flow I suggest to implement:
1. Follow the Reuse Cards Guide[1] 
2. Attach the resulting Payment Method to the Customer (retrieve it from setupIntent.payment_method)
3. Update the default payment method on the Customer[2] or Subscription[3].
After that, the next invoices will be charged from this Payment Method.

**Scenario 2 (collect a new Payment Method after a failed payment)**
The first part here is to bring the customer back online (via notifications: e-mail/SMS)
I suggest the following flow for when the Customer is back online: 

1. Collect a new Payment Method (PM) on the Frontend and pass the pm_id to the backend
2. Update the existing subscription.last_invoice.payment_intent with the new PM and try to confirm the Payment Intent (PI)
3. If the PI requires_action return the client secret associated with the payment intent to the frontend
4. Frontend uses client secret to carry out 3DS
    1. If 3DS is successful, the payment is taken and the subscription is active again
    2. If 3DS is not successful, you start again from Step 1 (Collect a new PM)
5. After the payment was successful:
    1. Attach the resulting Payment Method to the Customer
    2. Update the default payment method on the Customer[2] or Subscription[3]

If you have any other questions, please let me know and happy to help. 

[1] Reuse Payment Methods without an initial payment: https://stripe.com/docs/payments/cards/saving-cards-without-payment

[2] Default PM on Customer: https://stripe.com/docs/api/customers/object#customer_object-invoice_settings-default_payment_method
     This is useful if Customers can have only one default payment method for the subscriptions

[3] Default PM on Subscription: https://stripe.com/docs/api/subscriptions/object#subscription_object-default_payment_method 
     This is useful if Customers can have multiple subscriptions with multiple payment methods
