### ISSUE TITLE
3D Secure payment test card returns payment_intent: None

### ISSUE THREAD

**Issue by lifenautjoe** [stripe/sca-dev-chats#22]
## Topic

I'm trying to test the handling of 3DSecure on my checkout. Trying the 3DSecure cards here https://stripe.com/docs/payments/3d-secure/web , all of them return a `subscription` with `latest_invoice.payment_intent` None and `subscription_status` `active`.

## API

PaymentIntents

## Stripe Products

Billing

## Tech stack

- Backend language/frameworks: Django Python
- Frontend libraries/frameworks: Vue
- Stripe API version: 2019-05-16
- Stripe library version: Stripe/v1 NodeBindings/6.28.0

**Comment by lifenautjoe** [comment]
Anyone? :/

**Comment by ccnklc** [comment]
if it is your first time creating a subscription you should use pending_setup_intent.client_secret rather than looking for an invoice.

I hope it helps

**Comment by ccnklc** [comment]
Also not all 3d secure cards trigger 3ds if you don't have proper radar rules, try using this one which triggers it on all transactions 
4000000000003220

**Comment by lifenautjoe** [comment]
Thank you!

Aha, I do see the `pending_setup_intent`, but how come? In the Stripe test section, I see the payment marked as complete and subscription set to `active`...

Even if that's the case, should we handle these 3d secure things?

**Comment by lifenautjoe** [comment]
Ahá! Got it. Read through the docs. I'm using metered billing, therefore the pending_setup_intent.

Thank you @ccnklc !
