### ISSUE TITLE
Updating Payment Method for an Incomplete Subscription

### ISSUE THREAD

**Issue by tbell511** [stripe/sca-dev-chats#3]
## Topic

With the old API, using test card 4000000000000341 would successfully attach to the customer but attempts to charge would fail resulting in an error during the subscription create method `stripe.subscriptions.create`. 

With the new API, using the same test card results in an incomplete subscription. What's the best way to update the card for the customer and have the subscription try to charge again with the new card? 

Right now I am doing this...
```
// remove old card
await stripe.paymentMethods.detach(...)
// add new card
await stripe.paymentMethods.attach(...)
// set new card as customer default
await stripe.customers.update(customer, { 
    invoice_settings: { default_payment_method: paymentMethod.id }
},
// confirm payment intent that's associated with subscription with new payment method
await stripe.paymentIntents.confirm(..., { payment_method: paymentMethod.id })
```

I am probably making this much more complicated then it needs to be 😄 

Another quick related question.

With the old API, changing the customers default source would automatically retry failed payments associated with subscriptions.  It seems like this is not the case anymore with the new api and payment intents.  Is this right?

Thanks so much for doing the dev talks.  The past two videos you have done have been incredibly useful!
## API

What API does your question relate to: PaymentIntents, PaymentMethods, Subscriptions

## Stripe Products

What Stripe Products are you using: Billing

## Tech stack

- Backend language/frameworks: Node
- Frontend libraries/frameworks: n/a
- Stripe API version: 2019-05-16
- Stripe library version: 7.7.0

**Comment by thorsten-stripe** [comment]
Thanks for the detailed background, @tbell511! These are in essence the correct steps. I'd recommend the pull up the `confirm` request to make sure the new payment method works before attaching it. If you do so, you can optionally pass `save_payment_method:true` to automatically attach the payment method to the customer if the payment was successful: https://stripe.com/docs/api/payment_intents/confirm#confirm_payment_intent-save_payment_method

Regarding automatic retries when you update the source on a customer: this has indeed been deprecated with the deprecation of the `default_source` on the customer object. 

Hope this helps :) please reopen the issue if you have a followup question.
