### ISSUE TITLE
paymentIntent requires_action webhook

### ISSUE THREAD

**Issue by tbell511** [stripe/sca-dev-chats#4]
## Topic

I am trying to find the best way to handle this scenario.

A user of ours signs up with the following flow for a monthly subscription.

1. `stripe.createPaymentMethod` in frontend
2. `stripe.customers.create` with payment method
3. `stripe.subscriptions.create` with customer
4.  Results in incomplete subscription with `requires_action`
5.  return `client_secret` to frontend
6. use `stripe.handleCardPayment` with `client_secret` 
7. User authenticates payment and life is good for 30 days

8. stripe billing attempts to renew the subscription 30 days later.
9. Payment fails because it needs authentication...

What happens after this? What type of webhooks should we listen for to know that the user needs to authenticate their payment? I don't see any webhooks for `payment_intent.requires_action` and the `payment_intent.payment_failed` webhook doesn't seem to trigger for `requires_action` status but only for `requires_payment_method`

Thanks!

## API

What API does your question relate to: PaymentIntents

## Stripe Products

What Stripe Products are you using: Billing

## Tech stack

- Backend language/frameworks: Node
- Frontend libraries/frameworks: n/a
- Stripe API version: 2019-05-16
- Stripe library version: 7.7.0

**Comment by thorsten-stripe** [comment]
Hey @tbell511 thanks for your question. While the PaymentIntent itself does not have a `requires_action` event (the only way to move a PaymentIntent into `requires_action` state outside of billing is by a request from either your backend or your frontend). Therefore for billing there is a specific event for this scenario on the invoice object:`invoice.payment_action_required` (https://stripe.com/docs/api/events/types#event_types-invoice.payment_action_required)

Note that if you're handling this yourself, you probably don't want Stripe to also send emails to your customers for this scenario: https://stripe.com/docs/billing/migration/strong-customer-authentication#3ds-payment-settings

Hope this helps :) please reopen the issue if you have a followup question.

**Comment by tbell511** [comment]
Brilliant! Thank you!
