### ISSUE TITLE
Adding a setup fee to subscription

### ISSUE THREAD

**Issue by tbell511** [stripe/sca-dev-chats#5]
## Topic

Looking forward to the Dev Chat tomorrow! I've got another question for you guys. It's about adding one time setup fees to subscriptions.  

This is what I do currently and it works great.

// create customer with token (will use paymentMethod for SCA)
1. `stripe.customers.create`

// add invoice line item for the "setup fee"

2. `stripe.invoiceItems.create`

// then create the subscription

3. `stripe.subscriptions.create`

Should I use this same process for SCA? 

Thanks!

## API

What API does your question relate to: n/a

## Stripe Products

What Stripe Products are you using: Billing

## Tech stack

- Backend language/frameworks: Node
- Frontend libraries/frameworks: n/a
- Stripe API version: <2019-05-16>
- Stripe library version: 7.8.0

**Comment by thorsten-stripe** [comment]
Hey @tbell511, yes, that logic still works. Adding the invoice item to the customer will mean that it (the invoice item) will be added to the customer's next invoice. When you create the subscription it will create the invoice and add all the customer's invoice items to it. Then the invoice creates the PaymentIntent and if it requires SCA the subscription will go into `incomplete` state, in which case you call `handleCardPayment` on it on the frontend. 

One note regarding Tokens vs. PaymentMethods: Subscriptions are backwards compatible, meaning you can use them with both Tokens and PaymentMethods: https://stripe.com/docs/billing/migration/strong-customer-authentication#grandfathering
