### ISSUE TITLE
Notify user during off session

### ISSUE THREAD

**Issue by soju7** [stripe/sca-dev-chats#6]
## Topic

How the application get notified when the issuer prompt authentication during off-session? so i can change the business logic to prompt user again for authentication.is their any web hook for that? i made some research. can i use `payment_intent.payment_failed` webhook ?
## API

What API does your question relate to: PaymentIntents

## Stripe Products

What Stripe Products are you using: Billing

## Tech stack

- Backend language/frameworks: PHP>
- Frontend libraries/frameworks: Vue

**Comment by thorsten-stripe** [comment]
Thanks @soju7 I think the answer here should help you: https://github.com/stripe/sca-dev-chats/issues/4
