### ISSUE TITLE
stripe.setApiVersion

### ISSUE THREAD

**Issue by tbell511** [stripe/sca-dev-chats#9]
## Topic

Is it possible to use multiple API versions at the same time while my company upgrades our platform to the latest stripe version?

Our codebase has two parts to it.

1. Our own billing system (to charge our own customers)
2. And our stripe connect side (to use the stripe API on behalf of our customers)

We would like to roll out our upgrade in stages. As of today we finished upgrading our own billing system by using `stripe.setApiVersion("2019-05-16")`

Our connect side is still using `stripe.setApiVersion("2018-07-27")`

The API set in our stripe account dashboard is "2018-07-27". I figure we won't officially upgrade that until both parts of our system are upgraded.

Are there any problems with doing this?  One thing I would like to point out, are both sides of our platform run in the same Node process.  We import Stripe into our files with `const stripe = require("stripe")(process.env.STRIPE_KEY)`

I am hoping this is fine, but I have a feeling it's not 😁 

## Stripe Products

What Stripe Products are you using: Connect, Billing

## Tech stack

- Backend language/frameworks: Node
- Frontend libraries/frameworks: n/a
- Stripe API version: 2018-07-27
- Stripe library version: 7.8.0

**Comment by thorsten-stripe** [comment]
@tbell511 that's a completely legitimate approach of updating your integration in stages, see also: https://stripe.com/docs/upgrades#how-can-i-upgrade-my-api

One thing to watch out for is your Dashboard API version affects the shape of both your webhook events as well as the objects received with Stripe.js methods such as handleCardPayment and confirmPaymentIntent.

**Comment by tbell511** [comment]
Hi Thor, thank you!

Quick question, how do you override a single webhoook endpoint version? In the stripe docs it mentions "For webhooks, you can override the version of a single test webhook endpoint in your Dashboard."

I don't see an option for this though.

**Comment by tbell511** [comment]
Thanks Thor!
